### ISSUE TITLE
Support CB1

### ISSUE THREAD

**Issue by jscancella** [mainsail-crew/MainsailOS#192]
### Is your feature request related to a problem? Please describe

CB1 uses the allwinner h616 chip which needs custom kernel changes

### Describe the solution you'd like

a mainsail OS image that supports CB1 so that a RatOS image can easily be created

### Describe alternatives you've considered

Right now I manually go through the custompios steps after loading the official CB1 image from BTT''s repo, and then custom create an image afterwards. This is time consuming and error prone.

**Comment by meteyou** [comment]
Thx for your FR. We have no plans to add or create a CB1 mainsailOS build because BTT already provides a preinstalled Klipper/moonraker/mainsail image, which is very close to a mainsailOS build. (https://github.com/bigtreetech/CB1/releases/tag/V2.2.1)

And there is also no need to have a mainsailOS build that RatOS can support. RatOS have only to use our multi-image workflow and can use the base image from BTT. The BTT image is already bullseye, which is very important for the current workflow from mainsailOS.
