### ISSUE TITLE
Mainsail OS Fresh images network drop after attempting update

### ISSUE THREAD

**Issue by domocorn** [mainsail-crew/MainsailOS#234]
### What happened

On a fresh install of MainsailOS using the Raspberry Pi Imager on a Raspberry Pi Zero W V1.1 I ssh into the pi and run the "sudo apt update" command and shortly after the pi stops pinging at all.

(This also happens on the standard pi os lite 32 bit clean install)

### What did you expect to happen

That the Pi would update and not disconnect from network

### How to reproduce

Clean install of OS and running the update command.

### Additional information

![image](https://github.com/mainsail-crew/MainsailOS/assets/61746117/a0360793-0e32-4f8e-a740-82025ba56f12)

**Comment by meteyou** [comment]
This is the WiFi driver from raspberry. When your router change the frequency automatically, the raspi will lost the connection. You can try to use sonar for reconnects, but this also cannot fix the bad driver.

You can also report this issue to raspberry (because mainsailOS is just a raspberry pi is lite with preinstalled software. Nothing more).
