### ISSUE TITLE
[Feature Request] Notepad/sticky note with persistence displayed on Mainsail dashboard

### ISSUE THREAD

**Issue by Imburr** [mainsail-crew/MainsailOS#305]
### Is your feature request related to a problem? Please describe

This is not related to a problem.

### Describe the solution you'd like

I take notes as I go, when modifying, printing, etc. Obviously for code noes I use comments, but sometimes I would like a sticky note to remind me of something, or notate something that I did for this print, etc. It would be great to have a text based scratch pad which saved between reboots. Then I could leave myself a note without fear of accidentally closing notepad, or my PC rebooting, or my kids shutting my PC off.

### Describe alternatives you've considered

I us VS Code mostly, and I have saved printer notes. But often I just need something temporary, and opening up my file and editing it is a bother.

**Comment by meteyou** [comment]
Thx for your request, but first of all, this is the repo of MainsailOS and not Mainsail. I don't know, why people create FRs for Mainsail in the MainsailOS repo. MainsailOS is "just a preinstalled RPI image with Mainsail, Moonraker, Klipper"...

So if you have FRs related to the Webinterface (which is Mainsail), then pls create it in the Mainsail repo and not in repos "which just use Mainsail"...

Answer to the FR itself:
This FR comes multiple times to multiple different positions in Mainsail and to be honest. Mainsail is a 3D printer interface. not a "Notetaking app". many users already use "there own note app" like Obsidian, Inkdrop, Notion or anything else and then this function would be not compatible with there solution. so it would only create issues.
Next negative point would be, then User A (like you) need it on the dashboard. the User would need it inside the text editor and more. this would be a "never ending story". So in my eyes, its just a better solution to use a separate note taking app instead of implementing a "really stipe down version of anything like a note taking app" inside a complete different app/webinterface.

furthermore, i am sure that your browser also offers a whole series of extensions that would also provide such a function... We try to concentrate us on Klipper/Moonraker/3d printer functions right now to implement in Mainsail.
